//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carbon.Example.Desktop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carbon.Example.Desktop.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout must be between 10 and 60 seconds..
        /// </summary>
        public static string AuthErrorBadTimeout {
            get {
                return ResourceManager.GetString("AuthErrorBadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Base Uri incorrect format..
        /// </summary>
        public static string AuthErrorBadUri {
            get {
                return ResourceManager.GetString("AuthErrorBadUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADO Connection String is required..
        /// </summary>
        public static string AuthErrorNeedAdo {
            get {
                return ResourceManager.GetString("AuthErrorNeedAdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCS Licensing Base Address is required.
        /// </summary>
        public static string AuthErrorNeedBaseUri {
            get {
                return ResourceManager.GetString("AuthErrorNeedBaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id is required..
        /// </summary>
        public static string AuthErrorNeedId {
            get {
                return ResourceManager.GetString("AuthErrorNeedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is required..
        /// </summary>
        public static string AuthErrorNeedName {
            get {
                return ResourceManager.GetString("AuthErrorNeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string AuthErrorNeedPass {
            get {
                return ResourceManager.GetString("AuthErrorNeedPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Key is required..
        /// </summary>
        public static string AuthErrorNeedProdKey {
            get {
                return ResourceManager.GetString("AuthErrorNeedProdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Credentials.
        /// </summary>
        public static string AuthHeadLicCreds {
            get {
                return ResourceManager.GetString("AuthHeadLicCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing Provider.
        /// </summary>
        public static string AuthHeadLicProv {
            get {
                return ResourceManager.GetString("AuthHeadLicProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADO Connection String.
        /// </summary>
        public static string AuthlabelAdoConnect {
            get {
                return ResourceManager.GetString("AuthlabelAdoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key (optional).
        /// </summary>
        public static string AuthLabelApiKey {
            get {
                return ResourceManager.GetString("AuthLabelApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing service base Uri.
        /// </summary>
        public static string AuthLabelBaseUri {
            get {
                return ResourceManager.GetString("AuthLabelBaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayes Price.
        /// </summary>
        public static string AuthLabelBPr {
            get {
                return ResourceManager.GetString("AuthLabelBPr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Licence.
        /// </summary>
        public static string AuthLabelGetLic {
            get {
                return ResourceManager.GetString("AuthLabelGetLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AuthLabelPass {
            get {
                return ResourceManager.GetString("AuthLabelPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Key.
        /// </summary>
        public static string AuthLabelProdKey {
            get {
                return ResourceManager.GetString("AuthLabelProdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Centre.
        /// </summary>
        public static string AuthLabelRCS {
            get {
                return ResourceManager.GetString("AuthLabelRCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string AuthLabelRemember {
            get {
                return ResourceManager.GetString("AuthLabelRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string AuthLabelTimeout {
            get {
                return ResourceManager.GetString("AuthLabelTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string AuthLabelUserId {
            get {
                return ResourceManager.GetString("AuthLabelUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string AuthLabelUserName {
            get {
                return ResourceManager.GetString("AuthLabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating - Please wait....
        /// </summary>
        public static string BusyAuthenticating {
            get {
                return ResourceManager.GetString("BusyAuthenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this report?\n\n{0}.
        /// </summary>
        public static string DeleteTableConfirmPrompt {
            get {
                return ResourceManager.GetString("DeleteTableConfirmPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report cannot be deleted because it is not under the TOC user node of your authenticated name {0}..
        /// </summary>
        public static string DeleteTableNotOwner {
            get {
                return ResourceManager.GetString("DeleteTableNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LogColHeadCat {
            get {
                return ResourceManager.GetString("LogColHeadCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string LogColHeadMessage {
            get {
                return ResourceManager.GetString("LogColHeadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        public static string LogColHeadThread {
            get {
                return ResourceManager.GetString("LogColHeadThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string LogColHeadTime {
            get {
                return ResourceManager.GetString("LogColHeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close Licence.
        /// </summary>
        public static string MenuFileCloseLicText {
            get {
                return ResourceManager.GetString("MenuFileCloseLicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuFileExitText {
            get {
                return ResourceManager.GetString("MenuFileExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Get Licence.
        /// </summary>
        public static string MenuFileGetLicText {
            get {
                return ResourceManager.GetString("MenuFileGetLicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFileText {
            get {
                return ResourceManager.GetString("MenuFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _GitHub.
        /// </summary>
        public static string MenuHelpGithubText {
            get {
                return ResourceManager.GetString("MenuHelpGithubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHelpText {
            get {
                return ResourceManager.GetString("MenuHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Report No.{0}.
        /// </summary>
        public static string NewReportName {
            get {
                return ResourceManager.GetString("NewReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axes.
        /// </summary>
        public static string NodeLabelAxes {
            get {
                return ResourceManager.GetString("NodeLabelAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exec TOC.
        /// </summary>
        public static string NodeLabelExecToc {
            get {
                return ResourceManager.GetString("NodeLabelExecToc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full TOC.
        /// </summary>
        public static string NodeLabelFullToc {
            get {
                return ResourceManager.GetString("NodeLabelFullToc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple TOC.
        /// </summary>
        public static string NodeLabelSimpleToc {
            get {
                return ResourceManager.GetString("NodeLabelSimpleToc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vartrees (named).
        /// </summary>
        public static string NodeLabelVtNamed {
            get {
                return ResourceManager.GetString("NodeLabelVtNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vartrees (real).
        /// </summary>
        public static string NodeLabelVtReal {
            get {
                return ResourceManager.GetString("NodeLabelVtReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Selection.
        /// </summary>
        public static string NoSelect {
            get {
                return ResourceManager.GetString("NoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters.
        /// </summary>
        public static string SaveErrorBadChars {
            get {
                return ResourceManager.GetString("SaveErrorBadChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank path segment.
        /// </summary>
        public static string SaveErrorBlankSeg {
            get {
                return ResourceManager.GetString("SaveErrorBlankSeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save name required.
        /// </summary>
        public static string SaveErrorRequired {
            get {
                return ResourceManager.GetString("SaveErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading or trailing space.
        /// </summary>
        public static string SaveErrorSpace {
            get {
                return ResourceManager.GetString("SaveErrorSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report name can be a plain name like &apos;My&amp;#xa0;Report&apos; or it can be prefixed with a path like &apos;Billing/June/My&amp;#xa0;Report&apos;. Any existing report with the same name will overwritten..
        /// </summary>
        public static string SaveInstruct {
            get {
                return ResourceManager.GetString("SaveInstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path/Name.
        /// </summary>
        public static string SaveLabelName {
            get {
                return ResourceManager.GetString("SaveLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string TabLinesHead {
            get {
                return ResourceManager.GetString("TabLinesHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string TabLogHead {
            get {
                return ResourceManager.GetString("TabLogHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification.
        /// </summary>
        public static string TabSpecHead {
            get {
                return ResourceManager.GetString("TabSpecHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Report.
        /// </summary>
        public static string WorkTitleDeleteReport {
            get {
                return ResourceManager.GetString("WorkTitleDeleteReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        public static string WorkTitleGentab {
            get {
                return ResourceManager.GetString("WorkTitleGentab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep load axis.
        /// </summary>
        public static string WorkTitleLoadAxis {
            get {
                return ResourceManager.GetString("WorkTitleLoadAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load raw table lines.
        /// </summary>
        public static string WorkTitleLoadLines {
            get {
                return ResourceManager.GetString("WorkTitleLoadLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep load variable.
        /// </summary>
        public static string WorkTitleLoadVar {
            get {
                return ResourceManager.GetString("WorkTitleLoadVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep load real vartree.
        /// </summary>
        public static string WorkTitleLoadVartree {
            get {
                return ResourceManager.GetString("WorkTitleLoadVartree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Report.
        /// </summary>
        public static string WorkTitleNewReport {
            get {
                return ResourceManager.GetString("WorkTitleNewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open and deep load job.
        /// </summary>
        public static string WorkTitleOpenLoadJob {
            get {
                return ResourceManager.GetString("WorkTitleOpenLoadJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Report.
        /// </summary>
        public static string WorkTitleSaveReport {
            get {
                return ResourceManager.GetString("WorkTitleSaveReport", resourceCulture);
            }
        }
    }
}
